// Package swagger Code generated by swaggo/swag. DO NOT EDIT
package swagger

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/account/change": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Starts the process of changing account email or phone number",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Account"
                ],
                "summary": "Initiate account change",
                "parameters": [
                    {
                        "description": "Account change details",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/services.ChangeAccountForm"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/account/change/complete": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Completes the process of changing account email or phone number",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Account"
                ],
                "summary": "Complete account change",
                "parameters": [
                    {
                        "description": "Account change completion details",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/services.CompleteChangeAccountForm"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/account/create": {
            "post": {
                "description": "Creates a new user account with the provided details",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Account"
                ],
                "summary": "Create a new user account",
                "parameters": [
                    {
                        "description": "Account creation details",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/services.CreateAccountForm"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/account/current": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Retrieves details of the authenticated user",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Account"
                ],
                "summary": "Get current user account",
                "responses": {}
            }
        },
        "/account/password/change": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Changes the password for the authenticated user",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Account"
                ],
                "summary": "Change the current password",
                "parameters": [
                    {
                        "description": "Password change details",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/services.ChangePasswordForm"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/account/password/reset": {
            "post": {
                "description": "Starts the process of resetting the password for the account",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Account"
                ],
                "summary": "Initiate password reset",
                "parameters": [
                    {
                        "description": "Password reset details",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/services.ResetPasswordForm"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/account/password/reset/complete": {
            "post": {
                "description": "Completes the password reset process using the received token",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Account"
                ],
                "summary": "Complete password reset",
                "parameters": [
                    {
                        "description": "Password reset completion details",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/services.CompleteResetPasswordForm"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/account/signin": {
            "post": {
                "description": "Authenticates a user with email and password",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Account"
                ],
                "summary": "Sign in to an existing account",
                "parameters": [
                    {
                        "description": "Sign-in credentials",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/services.SignInForm"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/account/signin/refresh": {
            "post": {
                "description": "Authenticates a user using a refresh token to obtain new access tokens",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Account"
                ],
                "summary": "Sign in using a refresh token",
                "parameters": [
                    {
                        "description": "Refresh token details",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/services.SignInWithRefreshTokenForm"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/account/signout": {
            "post": {
                "description": "Logs out the user and invalidates the session/token",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Account"
                ],
                "summary": "Sign out of the current account",
                "parameters": [
                    {
                        "description": "Sign-out request details",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/services.SignOutForm"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/account/verify": {
            "post": {
                "description": "Starts the verification process for the account (email or phone)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Account"
                ],
                "summary": "Initiate account verification",
                "parameters": [
                    {
                        "description": "Verification details",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/services.VerifyAccountForm"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/account/verify/complete": {
            "post": {
                "description": "Completes the verification process using the received token",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Account"
                ],
                "summary": "Complete account verification",
                "parameters": [
                    {
                        "description": "Verification completion details",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/services.CompleteVerifyAccountForm"
                        }
                    }
                ],
                "responses": {}
            }
        }
    },
    "definitions": {
        "services.ChangeAccountForm": {
            "type": "object",
            "required": [
                "newUsername"
            ],
            "properties": {
                "newUsername": {
                    "type": "string",
                    "maxLength": 256
                }
            }
        },
        "services.ChangePasswordForm": {
            "type": "object",
            "required": [
                "newPassword",
                "oldPassword"
            ],
            "properties": {
                "newPassword": {
                    "type": "string"
                },
                "oldPassword": {
                    "type": "string"
                }
            }
        },
        "services.CompleteChangeAccountForm": {
            "type": "object",
            "required": [
                "newUsername",
                "token"
            ],
            "properties": {
                "newUsername": {
                    "type": "string",
                    "maxLength": 256
                },
                "token": {
                    "type": "string"
                }
            }
        },
        "services.CompleteResetPasswordForm": {
            "type": "object",
            "required": [
                "newPassword",
                "token",
                "username"
            ],
            "properties": {
                "newPassword": {
                    "type": "string"
                },
                "token": {
                    "type": "string"
                },
                "username": {
                    "type": "string",
                    "maxLength": 256
                }
            }
        },
        "services.CompleteVerifyAccountForm": {
            "type": "object",
            "required": [
                "token",
                "username"
            ],
            "properties": {
                "token": {
                    "type": "string"
                },
                "username": {
                    "type": "string",
                    "maxLength": 256
                }
            }
        },
        "services.CreateAccountForm": {
            "type": "object",
            "required": [
                "firstName",
                "lastName",
                "password",
                "username"
            ],
            "properties": {
                "firstName": {
                    "type": "string",
                    "maxLength": 256
                },
                "lastName": {
                    "type": "string",
                    "maxLength": 256
                },
                "password": {
                    "type": "string"
                },
                "username": {
                    "type": "string",
                    "maxLength": 256
                },
                "validateOnly": {
                    "type": "boolean"
                }
            }
        },
        "services.ResetPasswordForm": {
            "type": "object",
            "required": [
                "username"
            ],
            "properties": {
                "username": {
                    "type": "string",
                    "maxLength": 256
                }
            }
        },
        "services.SignInForm": {
            "type": "object",
            "required": [
                "password",
                "username"
            ],
            "properties": {
                "password": {
                    "type": "string"
                },
                "username": {
                    "type": "string",
                    "maxLength": 256
                }
            }
        },
        "services.SignInWithRefreshTokenForm": {
            "type": "object",
            "required": [
                "refreshToken"
            ],
            "properties": {
                "refreshToken": {
                    "type": "string"
                }
            }
        },
        "services.SignOutForm": {
            "type": "object",
            "required": [
                "refreshToken"
            ],
            "properties": {
                "global": {
                    "type": "boolean"
                },
                "refreshToken": {
                    "type": "string"
                }
            }
        },
        "services.VerifyAccountForm": {
            "type": "object",
            "required": [
                "username"
            ],
            "properties": {
                "username": {
                    "type": "string",
                    "maxLength": 256
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Konabra API",
	Description:      "Konabra is a smart, community-powered transport and road safety platform for Ghana. This API supports live incident reporting, road condition updates, and data analytics integration.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
