basePath: /
definitions:
  services.AccountVerificationForm:
    properties:
      username:
        maxLength: 256
        type: string
    required:
    - username
    type: object
  services.CompleteAccountVerificationForm:
    properties:
      code:
        type: string
      username:
        maxLength: 256
        type: string
    required:
    - code
    - username
    type: object
  services.CreateAccountForm:
    properties:
      firstName:
        maxLength: 256
        type: string
      lastName:
        maxLength: 256
        type: string
      password:
        type: string
      username:
        maxLength: 256
        type: string
    required:
    - firstName
    - lastName
    - password
    - username
    type: object
  services.SignInForm:
    properties:
      password:
        type: string
      username:
        maxLength: 256
        type: string
    required:
    - password
    - username
    type: object
info:
  contact: {}
  description: Konabra is a smart, community-powered transport and road safety platform
    for Ghana. This API supports live incident reporting, road condition updates,
    and data analytics integration.
  title: Konabra API
  version: "1.0"
paths:
  /account/create:
    post:
      consumes:
      - application/json
      description: Creates a new user account with the provided details
      parameters:
      - description: Account creation details
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/services.CreateAccountForm'
      produces:
      - application/json
      responses: {}
      summary: Create a new user account
      tags:
      - Account
  /account/me:
    get:
      consumes:
      - application/json
      description: Retrieves details of the authenticated user
      produces:
      - application/json
      responses: {}
      security:
      - BearerAuth: []
      summary: Get current user account
      tags:
      - Account
  /account/signin:
    post:
      consumes:
      - application/json
      description: Authenticates a user with email and password
      parameters:
      - description: Sign-in credentials
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/services.SignInForm'
      produces:
      - application/json
      responses: {}
      summary: Sign in to an existing account
      tags:
      - Account
  /account/verify:
    post:
      consumes:
      - application/json
      description: Sends a verification email or SMS to the user
      parameters:
      - description: Verification request details
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/services.AccountVerificationForm'
      produces:
      - application/json
      responses: {}
      summary: Send account verification
      tags:
      - Account
  /account/verify/complete:
    post:
      consumes:
      - application/json
      description: Completes the account verification process using a token
      parameters:
      - description: Verification completion details
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/services.CompleteAccountVerificationForm'
      produces:
      - application/json
      responses: {}
      summary: Complete account verification
      tags:
      - Account
swagger: "2.0"
