basePath: /
definitions:
  problems.Problem:
    properties:
      detail:
        description: Human-readable explanation
        type: string
      errors:
        additionalProperties:
          type: string
        description: Field validation errors
        type: object
      status:
        description: HTTP status code
        type: integer
      title:
        description: Short summary of the problem
        type: string
      type:
        description: A URI reference to the problem type
        type: string
    type: object
  services.CreateAccountForm:
    properties:
      firstName:
        maxLength: 256
        type: string
      lastName:
        maxLength: 256
        type: string
      password:
        type: string
      username:
        maxLength: 256
        type: string
    required:
    - firstName
    - lastName
    - password
    - username
    type: object
  services.SignInForm:
    properties:
      password:
        type: string
      username:
        maxLength: 256
        type: string
    required:
    - password
    - username
    type: object
info:
  contact: {}
  description: Konabra is a smart, community-powered transport and road safety platform
    for Ghana. This API supports live incident reporting, road condition updates,
    and data analytics integration.
  title: Konabra API
  version: "1.0"
paths:
  /account/create:
    post:
      consumes:
      - application/json
      description: Create a new user account with the provided information
      parameters:
      - description: Account creation details
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/services.CreateAccountForm'
      produces:
      - application/json
      responses:
        "200":
          description: Account created successfully
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Invalid request body
          schema:
            $ref: '#/definitions/problems.Problem'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/problems.Problem'
      summary: Create a new account
      tags:
      - Identity
  /account/me:
    get:
      description: Get information about the currently authenticated user account
      produces:
      - application/json
      responses:
        "200":
          description: Account information retrieved successfully
          schema:
            additionalProperties: true
            type: object
        "401":
          description: User not authenticated
          schema:
            $ref: '#/definitions/problems.Problem'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/problems.Problem'
      security:
      - ApiKeyAuth: []
      summary: Get current account information
      tags:
      - Identity
  /account/signin:
    post:
      consumes:
      - application/json
      description: Sign in to an existing user account with the provided credentials
      parameters:
      - description: Account sign-in credentials
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/services.SignInForm'
      produces:
      - application/json
      responses:
        "200":
          description: Account signed in successfully
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Invalid request body
          schema:
            $ref: '#/definitions/problems.Problem'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/problems.Problem'
      summary: Sign in to an account
      tags:
      - Identity
swagger: "2.0"
