basePath: /
definitions:
  services.WeatherForecast:
    properties:
      date:
        type: string
      summary:
        type: string
      temperatureC:
        type: integer
    type: object
host: localhost:8080
info:
  contact: {}
  description: This is a sample server using Gin and Swagger. CLI => swag init -g
    cmd/app/main.go -o ./docs/swagger
  title: Example API
  version: "1.0"
paths:
  /weatherforecast:
    get:
      description: Returns a list of weather forecasts.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/services.WeatherForecast'
            type: array
      summary: Get Weather Forecasts
      tags:
      - Weather
swagger: "2.0"
